server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: "*"

application:
  version: "2020.1.13"

#spring:
#  data:
#    mongodb:
#      host: 192.168.191.198
#      port: 27017
#      database: user

#logging:
#  level:
#    org.springframework: debug