server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: "*"

application:
  version: "2020.1.13"

#spring:
#  data:
#    mongodb:
#      host: 192.168.191.198
#      port: 27017
#      database: user

spring:
  rabbitmq:
    host: "192.168.191.198"
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
        acknowledge-mode: manual
        missing-queues-fatal: false

    username: "root"
    password: "password"
    virtual-host: "vhos"